
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-web-app
  template:
    metadata:
      labels:
        app: go-web-app
    spec:
      containers:
      - name: go-web-app
        image: revanthreddydatla/go-web-app:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: go-web-app-service
spec:
  type: NodePort
  selector:
    app: go-web-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-web-app-ingress
  annotations:
    # Add any necessary annotations for your Ingress Controller (e.g., NGINX Ingress Controller)
    # ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/limit-connections: "10"
spec:
  ingressClassName: nginx # Specify the Ingress Controller to use
  rules:
    - http:
        paths:
          - path: / # Define a path for routing
            pathType: Prefix # Can be Prefix, Exact, or ImplementationSpecific
            backend:
              service:
                name: go-web-app-service # Name of the Kubernetes Service
                port:
                  number: 8080 # Port of the Kubernetes Service
